# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FireBlog
tagline:          'FireZenk's dev blog'
description:      'Meet a crazy #AndroidDev and their also crazy ideas'
url:              https://firezenk.github.io
baseurl:          /

author:
  name:           'Jorge Garrido'
  url:            https://twitter.com/FireZenk

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/FireZenk/firezenk.github.io
